do $$ declare r record; task uuid; ordinary uuid; reward uuid; redemption uuid; penalty uuid; req uuid; rev bigint; i int; bal bigint; cnt int;
begin
 perform set_config('request.jwt.claim.role','authenticated',false);
 perform set_config('request.jwt.claim.sub','a0000000-0000-0000-0000-000000000001',false);
 select * into r from create_affairs_task(gen_random_uuid(),'{"title":"Ordinary"}'); ordinary:=r.object_id;
 select * into r from complete_affairs_task(gen_random_uuid(),ordinary,1,true);
 if r.coin_delta<>0 or r.balance_coins<>0 then raise exception 'ordinary rewarded'; end if;
 perform reopen_affairs_task(gen_random_uuid(),ordinary,2);
 begin perform update_affairs_task(gen_random_uuid(),ordinary,3,'{"title":"Ordinary","is_core":true,"core_reason":"Goal","completion_criteria":"Done"}'); raise exception 'retroactive core'; exception when others then if sqlerrm<>'core_eligibility_locked' then raise; end if; end;
 select * into r from create_affairs_task(gen_random_uuid(),'{"title":"Core","is_core":true,"core_reason":"Goal","completion_criteria":"Done"}'); task:=r.object_id;
 req:=gen_random_uuid(); select * into r from complete_affairs_task(req,task,1,true);
 if r.coin_delta<>1 or r.balance_coins<>1 then raise exception 'core reward'; end if;
 select * into r from complete_affairs_task(req,task,1,true);
 if not r.replayed then raise exception 'stale replay rejected'; end if;
 begin perform complete_affairs_task(gen_random_uuid(),task,2,true); raise exception 'repeat accepted'; exception when others then if sqlerrm<>'invalid_state_transition' then raise; end if; end;
 perform reopen_affairs_task(gen_random_uuid(),task,2);
 select * into r from complete_affairs_task(gen_random_uuid(),task,3,true);
 if r.coin_delta<>0 then raise exception 'reopen rewarded'; end if;
 perform undo_affairs_task_completion(gen_random_uuid(),task,4,'Mistaken');
 if (select balance_coins from vw_affairs_coin_balance where user_id=auth.uid())<>0 then raise exception 'undo missed old award'; end if;
 if exists(select 1 from affairs_progress_entries where task_id=task and voided_at is null) then raise exception 'undo contribution'; end if;
 perform complete_affairs_task(gen_random_uuid(),task,5,true);
 if (select count(*) from affairs_progress_entries where task_id=task and voided_at is null)<>1 then raise exception 'contribution duplicated'; end if;
 for i in 1..3 loop
 select * into r from create_affairs_task(gen_random_uuid(),'{"title":"Core","is_core":true,"core_reason":"Goal","completion_criteria":"Done"}');
 perform complete_affairs_task(gen_random_uuid(),r.object_id,1,true);
 end loop;
 select * into r from create_affairs_reward(gen_random_uuid(),'{"name":"User reward","price_coins":3}'); reward:=r.object_id;
 select * into r from redeem_affairs_reward(gen_random_uuid(),reward,1,3); redemption:=r.object_id;
 if r.balance_coins<>1 then raise exception 'redemption balance'; end if;
 perform update_affairs_reward(gen_random_uuid(),reward,1,'{"name":"Changed","price_coins":5,"is_active":true}');
 if (select name_snapshot from affairs_redemptions where id=redemption)<>'User reward' then raise exception 'snapshot changed'; end if;
 begin perform redeem_affairs_reward(gen_random_uuid(),reward,1,3); raise exception 'old price accepted'; exception when others then if sqlerrm<>'reward_price_changed' then raise; end if; end;
 req:=gen_random_uuid(); perform cancel_affairs_redemption(req,redemption,1);
 select * into r from cancel_affairs_redemption(req,redemption,1); if not r.replayed or r.balance_coins<>4 then raise exception 'refund replay'; end if;
 begin perform cancel_affairs_redemption(gen_random_uuid(),redemption,2); raise exception 'double refund'; exception when others then if sqlerrm<>'already_reversed' then raise; end if; end;
 perform update_affairs_reward(gen_random_uuid(),reward,2,'{"name":"Reward","price_coins":3,"is_active":true}');
 select * into r from redeem_affairs_reward(gen_random_uuid(),reward,3,3); redemption:=r.object_id;
 perform use_affairs_redemption(gen_random_uuid(),redemption,1);
 begin perform cancel_affairs_redemption(gen_random_uuid(),redemption,2); raise exception 'used refunded'; exception when others then if sqlerrm<>'redemption_already_used' then raise; end if; end;
 select * into r from record_affairs_penalty(gen_random_uuid(),null,'Manual only',now()-interval '1 day'); penalty:=r.object_id;
 if r.coin_delta<>-1 or r.balance_coins<>0 then raise exception 'penalty amount'; end if;
 perform reverse_affairs_penalty(gen_random_uuid(),penalty,1,'Mistaken');
 begin perform reverse_affairs_penalty(gen_random_uuid(),penalty,2,'Again'); raise exception 'double reversal'; exception when others then if sqlerrm<>'already_reversed' then raise; end if; end;
 perform record_affairs_penalty(gen_random_uuid(),null,'Manual',now()); perform record_affairs_penalty(gen_random_uuid(),null,'Manual',now());
 if (select balance_coins from vw_affairs_coin_balance where user_id=auth.uid())<>-1 then raise exception 'negative rejected'; end if;
 begin perform redeem_affairs_reward(gen_random_uuid(),reward,3,3); raise exception 'overspend'; exception when others then if sqlerrm<>'insufficient_coins' then raise; end if; end;
 if exists(select 1 from vw_affairs_coin_ledger l where balance_after<>(select sum(e.amount) from affairs_coin_events e where e.user_id=l.user_id and e.wallet_sequence<=l.wallet_sequence)) then raise exception 'ledger running sum'; end if;
 perform set_config('request.jwt.claim.sub','b0000000-0000-0000-0000-000000000002',false);
 begin perform complete_affairs_task(gen_random_uuid(),task,6,true); raise exception 'cross owner reward'; exception when others then if sqlerrm<>'not_found' then raise; end if; end;
end $$;
