import type { FinanceDataset } from "./types";

export const financeDataset: FinanceDataset = {
  asOf: "2026-09-02",
  accounts: [
    {
      id: "daily-checking",
      name: "日常账户",
      institution: "招商银行",
      type: "cash",
      balance: 21480.2,
    },
    {
      id: "reserve-savings",
      name: "储蓄账户",
      institution: "中国银行",
      type: "savings",
      balance: 36000,
    },
    {
      id: "long-term-investment",
      name: "长期投资",
      institution: "证券账户",
      type: "investment",
      balance: 72180,
    },
    {
      id: "travel-card",
      name: "旅行信用卡",
      institution: "Visa",
      type: "credit",
      balance: -1200,
    },
  ],
  transactions: [
    {
      id: "tx-rent",
      date: "2026-09-02",
      merchant: "房租",
      category: "居住",
      accountId: "daily-checking",
      amount: -3800,
      icon: "home",
    },
    {
      id: "tx-salary",
      date: "2026-09-01",
      merchant: "工资",
      category: "收入",
      accountId: "daily-checking",
      amount: 16800,
      icon: "briefcase",
    },
    {
      id: "tx-freelance",
      date: "2026-09-01",
      merchant: "项目收入",
      category: "收入",
      accountId: "daily-checking",
      amount: 1400,
      icon: "briefcase",
    },
    {
      id: "tx-transit",
      date: "2026-08-31",
      merchant: "交通",
      category: "交通",
      accountId: "travel-card",
      amount: -126,
      icon: "train",
    },
    {
      id: "tx-coffee",
      date: "2026-08-31",
      merchant: "咖啡",
      category: "餐饮",
      accountId: "travel-card",
      amount: -32,
      icon: "coffee",
    },
    {
      id: "tx-groceries",
      date: "2026-08-30",
      merchant: "盒马鲜生",
      category: "生活",
      accountId: "daily-checking",
      amount: -468,
      icon: "shopping-bag",
    },
    {
      id: "tx-dinner",
      date: "2026-08-29",
      merchant: "晚餐",
      category: "餐饮",
      accountId: "daily-checking",
      amount: -286,
      icon: "utensils",
    },
    {
      id: "tx-phone",
      date: "2026-08-28",
      merchant: "手机账单",
      category: "通讯",
      accountId: "daily-checking",
      amount: -129,
      icon: "phone",
    },
    {
      id: "tx-health",
      date: "2026-08-27",
      merchant: "健身会员",
      category: "健康",
      accountId: "travel-card",
      amount: -399,
      icon: "heart",
    },
  ],
  budgets: [
    { id: "housing", category: "居住", limit: 4500, spent: 3800, color: "terracotta" },
    { id: "food", category: "餐饮", limit: 1800, spent: 1260, color: "sand" },
    { id: "transport", category: "交通", limit: 800, spent: 486, color: "slate" },
    { id: "life", category: "生活", limit: 1200, spent: 968, color: "rose" },
  ],
  cashflow: [
    { month: "3月", income: 12800, expense: 7200 },
    { month: "4月", income: 15200, expense: 8100 },
    { month: "5月", income: 14600, expense: 7600 },
    { month: "6月", income: 17300, expense: 8900 },
    { month: "7月", income: 16700, expense: 9200 },
    { month: "8月", income: 19500, expense: 10300 },
    { month: "9月", income: 18200, expense: 9680 },
  ],
};
