'use client';
import Link from 'next/link';import type {AffairsProjectDetailData} from '../types';import {ActionForm,type AffairsAction} from './action-form';import {MilestoneEditor} from './milestone-editor';import {TaskList} from './task-list';import styles from './affairs.module.css';
import {ProgressEntryForm} from './progress-entry-form';
export function ProjectDetail({data,action}:{data:AffairsProjectDetailData;action:AffairsAction}){
 const {project:p}=data;const blocked=p.status==='archived'||p.status==='completed';return <section><header className={styles.sectionHeader}><div><span className={styles.eyebrow}>PROJECT</span><h1>{p.name}</h1><p>{p.outcome}</p></div><Link className={styles.secondaryButton} href={'/affairs/projects/'+p.id+'/edit'}>编辑项目</Link></header>
 {blocked?<div className={styles.notice}><p>请先恢复项目，再继续编辑或推进；历史记录保留。</p><ActionForm action={action} operation="set_affairs_project_status" identity={p} submitLabel="恢复项目"><input type="hidden" name="status" value="active"/><input type="hidden" name="outcome_confirmed" value="false"/></ActionForm></div>:<div className={styles.rowActions}><ActionForm action={action} operation="set_affairs_project_status" identity={p} submitLabel={p.status==='paused'?'恢复推进':'暂停项目'}><input type="hidden" name="status" value={p.status==='paused'?'active':'paused'}/><input type="hidden" name="outcome_confirmed" value="false"/></ActionForm><ActionForm action={action} operation="set_affairs_project_status" identity={p} submitLabel="归档项目"><input type="hidden" name="status" value="archived"/><input type="hidden" name="outcome_confirmed" value="false"/></ActionForm></div>}
 <section className={styles.section}><h2>阶段成果</h2>{p.progressRate===null?<p className={styles.muted}>尚未设置阶段成果</p>:<><progress max="1" value={p.progressRate} aria-label="项目阶段进度"/><p>{p.milestoneCompleted}/{p.milestoneTotal} · {Math.round(p.progressRate*100)}%</p></>}{data.milestones.map(m=><article className={styles.taskRow} key={m.id}><div><h3>{m.title}</h3><p className={styles.muted}>{m.completionCriteria}</p></div>{!blocked?<ActionForm action={action} operation="set_affairs_milestone_completed" identity={m} submitLabel={m.status==='completed'?'撤销阶段完成':'验收阶段'}><input type="hidden" name="completed" value={String(m.status!=='completed')}/></ActionForm>:<span>{m.status==='completed'?'已完成':'待验收'}</span>}</article>)}{!blocked?<><MilestoneEditor key={p.revision} project={p} milestones={data.milestones} action={action}/><ActionForm action={action} operation="set_affairs_project_status" identity={p} submitLabel="确认项目成果完成"><input type="hidden" name="status" value="completed"/><label className={styles.checkLabel}><input type="checkbox" name="outcome_confirmed" value="true" required/>确认已获得预期成果，所有阶段和核心行动已验收</label></ActionForm></>:null}</section>
 <TaskList tasks={data.tasks} projects={[p]} balance={data.balance} action={action} showAll/>
 {!blocked?<ProgressEntryForm projects={[p]} tasks={data.tasks} action={action} serverNowISO={data.serverNowISO}/>:null}
 <section className={styles.section}><h2>真实进展</h2>{data.progress.length?data.progress.map(e=><article className={styles.progressEntry} key={e.id}><p>{e.content}</p>{e.nextStep?<p className={styles.muted}>下次接续：{e.nextStep}</p>:null}<small>{new Date(e.occurredAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}{e.voidedAt?' · 已撤销：'+e.voidedReason:''}</small></article>):<p className={styles.muted}>暂无进展记录。</p>}</section></section>;
}

