'use client';
import {useState} from 'react';import Link from 'next/link';
import type {AffairsTask,AffairsProject} from '../types';import type {AffairsAction} from './action-form';import {ActionForm} from './action-form';
import styles from './affairs.module.css';
const labels={todo:'待开始',in_progress:'推进中',waiting:'等待',done:'已完成',cancelled:'已取消'};
export function TaskList({tasks,projects,balance,action,showAll=false}:{tasks:AffairsTask[];projects:AffairsProject[];balance:number;action:AffairsAction;showAll?:boolean}){
 const [all,setAll]=useState(showAll);const visible=all?tasks:tasks.filter(t=>!t.projectId&&!t.isCore);
 return <section><header className={styles.sectionHeader}><div><h2>{showAll?'行动':'零散事务'}</h2><p className={styles.muted}>核心行动完成 +1，杂事不发金币。当前 {balance} 金币。</p></div><Link href="/affairs/tasks/new" className={styles.secondaryButton}>新建行动</Link></header>{!showAll?<div className={styles.filters}><button className={!all?styles.selectedFilter:styles.filter} onClick={()=>setAll(false)}>零散事务</button><button className={all?styles.selectedFilter:styles.filter} onClick={()=>setAll(true)}>全部行动</button></div>:null}
 {visible.length===0?<p className={styles.empty}>暂无行动，可以先添加一件你想推进的事。</p>:<div className={styles.taskRows}>{visible.map(task=>{const project=projects.find(p=>p.id===task.projectId);const blocked=project?.status==='archived'||project?.status==='completed';return <article key={task.id} className={styles.taskRow}><div><Link href={'/affairs/tasks/'+task.id+'/edit'}><h3>{task.title}</h3></Link><p className={styles.muted}>{task.isCore?'核心行动':'普通事务'} · {labels[task.status]}{project?' · '+project.name:''}{task.dueDate?' · 截止 '+task.dueDate:''}</p>{task.waitingReason?<p>{task.waitingReason}</p>:null}</div><div className={styles.rowActions}><Link className={styles.textButton} href={'/affairs/tasks/'+task.id+'/edit'}>编辑</Link>{!blocked&&task.status!=='done'?<ActionForm action={action} operation="set_affairs_task_status" identity={task} submitLabel={task.status==='cancelled'?'恢复行动':'开始推进'}><input type="hidden" name="status" value={task.status==='cancelled'?'todo':'in_progress'}/><input type="hidden" name="waiting_reason" value=""/></ActionForm>:null}{blocked?<span className={styles.muted}>请先恢复项目</span>:null}</div></article>;})}</div>}</section>;
}

